addSbtPlugin("com.dwijnand"      % "sbt-travisci"  % "1.1.3")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"       % "1.1.2")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"  % "1.5.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"    % "5.2.0")
addSbtPlugin("io.get-coursier"   % "sbt-coursier"  % "1.0.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"  % "2.3")
addSbtPlugin("com.github.gseitz" % "sbt-release"   % "1.0.11")
addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "1.6.0-M5")
