addSbtPlugin("com.dwijnand"      % "sbt-travisci"     % "1.2.0")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"          % "2.0.1")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"     % "2.4.2")
addSbtPlugin("de.heikoseeberger" % "sbt-header"       % "5.6.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"     % "2.6")
addSbtPlugin("com.github.gseitz" % "sbt-release"      % "1.0.13")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"    % "1.6.1")
